#???????
spring:
  datasource:
    username: root
    password: ljw123456
    #url????????????????????????
    url: jdbc:mysql://127.0.0.1:3306/SpringDemo
    driver-class-name: com.mysql.cj.jdbc.Driver
#????
server:
  port: 9999

mybatis:
  # ?? mapper.xml ???
  mapper-locations: classpath:mapper/*.xml
  #????????,?????????????? mapper.xml ??????????????
  type-aliases-package: com.example.SpringDemo.JavaBean
  configuration:
    #???????????????????
    map-underscore-to-camel-case: true


